steps:
  # Install dependencies
  - name: node:11.1.0
    id: update
    entrypoint: yarn
    args: ['install', '--production']
    env:
      - 'NODE_ENV=production'

  # Build site
  - name: node:11.1.0
    id: build
    waitFor: ['update']
    entrypoint: yarn
    args: ['build']
    env:
      - 'NODE_ENV=production'

  # Upload build artifact to versioned subdirectory
  - name: 'gcr.io/cloud-builders/gsutil'
    id: backup
    waitFor: ['build']
    args:
      [
        '-m',
        'cp',
        '-z',
        'js,css,html',
        '-r',
        '/workspace/public',
        'gs://carlos-run-artifacts/$REVISION_ID',
      ]

  # Deploy build artifact
  - name: 'gcr.io/cloud-builders/gsutil'
    id: deploy
    waitFor: ['backup']
    args:
      [
        '-m',
        'rsync',
        '-r',
        '-d',
        'gs://carlos-run-artifacts/$REVISION_ID',
        'gs://carlos.run',
      ]

  # Set cache headers
  - name: 'gcr.io/cloud-builders/gsutil'
    id: cache
    waitFor: ['deploy']
    entrypoint: bash
    args:
      - '-c'
      - |
        gsutil -m setmeta -h "Cache-Control:public,max-age=0,must-revalidate" 'gs://carlos.run/**.html' && \
        gsutil -m setmeta -h "Cache-Control:public,max-age=31536000,immutable" 'gs://carlos.run/*.js' && \
        gsutil -m setmeta -h "Cache-Control:public,max-age=31536000,immutable" 'gs://carlos.run/*.css' && \
        gsutil -m setmeta -r -h "Cache-Control:public,max-age=31536000,immutable" 'gs://carlos.run/static'
