---
steps:
  # Install dependencies
  - name: node:11.1.0
    id: update
    entrypoint: yarn
    args: ['install', '--production']
    env:
      - 'NODE_ENV=production'

  # Build site
  - name: node:11.1.0
    id: build
    waitFor: ['update']
    entrypoint: yarn
    args: ['build']
    env:
      - 'NODE_ENV=production'

  # Deploy build artifact
  - name: 'gcr.io/cloud-builders/gsutil'
    id: deploy
    waitFor: ['build']
    entrypoint: bash
    args:
      - '-c'
      - |
        find public -name \* -print | gsutil -m cp -r -I gs://carlos.run

  # Upload build artifact to versioned subdirectory
  - name: 'gcr.io/cloud-builders/gsutil'
    id: backup
    waitFor: ['build']
    args: ['-m', 'rsync', '-r', '-d', 'public', 'gs://carlos-run-artifacts/$REVISION_ID']
