---
steps:
  # Install dependencies
  - name: node:11.1.0
    id: update
    entrypoint: yarn

  # Build site
  - name: node:11.1.0
    id: build
    waitFor: ['update']
    entrypoint: yarn
    args: ['build']

  # Deploy build artifact
  - name: 'gcr.io/cloud-builders/gsutil'
    id: deploy
    waitFor: ['build']
    args: ['-m', 'cp', '-R', 'public', 'gs://carlos.run']
    # args: ['-m', 'rsync', '-r', '-d', 'public', 'gs://carlos.run']

  # Upload build artifact to versioned subdirectory
  - name: 'gcr.io/cloud-builders/gsutil'
    id: backup
    waitFor: ['build']
    args: ['-m', 'rsync', '-r', '-d', 'public', 'gs://carlos-run-artifacts/$REVISION_ID']
